[[mgr.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm
''', "yank" ]


[[mgr.prepend_keymap]]
on   = "t"
run  = "shell --block --confirm 'kitty --working-directory $PWD'"
desc = "Open Kitty in the current directory"
